### ISSUE TITLE
Provide necessary steps to reproduce the results

### ISSUE THREAD

**Issue by shawkui** [damianliumin/non-adversarial_backdoor#2]
Dear authors,

I am interested in your method "Non-adversarial Backdoor” and I would like to reproduce your experiments. 

However, I found that your code lacks some critical details that are necessary for understanding and replicating your method. Specifically, you do not describe the **three backdoor detection techniques and the two relabeling strategies** that you use in your experiments.  Without them, it is difficult to compare your method to other methods.

Could you please provide more information about these techniques and strategies in your paper or in this repo?  This would help me and other researchers to better appreciate your contribution and assess its validity.

Thank you for your attention and cooperation. I look forward to hearing from you soon.

**Comment by minliu01** [comment]
Hi, I see you closed this issue yesterday. Do you still have any problem with the code?
For backdoor detection, we provide a simple implementation for LGA. You can also find links to the other two methods in README.md.
For relabeling, we provide the implementation of VD. You need to refer to the implementation of DBD (https://github.com/SCLBD/DBD) for the SSL-pretrained model in NC.
The details of these methods are also described in Sec 4.1 and Appendix.4.

**Comment by shawkui** [comment]
Thanks for your valuable feedback. Based on the Implementation of DBD (for relabel) and ABL (for detection), another implementation is now provided in https://github.com/SCLBD/BackdoorBench/blob/main/defense/nab.py to benchmark NAB with other methods.

**Comment by minliu01** [comment]
Great, thanks for your contribution!
